# ---------------
# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
# theme_color:
#   enable: true
#   main: "#49B1F5"
#   paginator: "#00C4B6"
#   button_hover: "#FF7242"
#   text_selection: "#00C4B6"
#   link_color: "#858585"
#   hr_color: "#A4D8FA"
#   tag_start_color: "#A4D8FA"
#   tag_end_color: "#1B9EF3"
#   header_text_color: "#EEEEEE"
#   footer_text_color: "#EEEEEE"

theme_color:
  enable: true
  main: "#000"
  paginator: "#000"
  button_hover: "#49B1F5"
  text_selection: "#000"
  link_color: "#000"
  hr_color: "#000"
  meta_color: "#000"

# Main menu navigation
menu:
  Home: /
  Categories: /categories
  Tags: /tags
  Archives: /archives
  About: /about

# Favicon
# ---------------
favicon: /img/favicon.ico

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: false
  manifest: /manifest.json
  # If you don't want to trouble, just ignore the following things
  # See https://realfavicongenerator.net/
  # theme_color: "#1B9EF3"
  # apple_touch_icon: /apple-touch-icon.png
  # favicon_32_32: /favicon-32x32.png
  # favicon_16_16: /favicon-16x16.png
  # mask_icon: /safari-pinned-tab.svg

# Highlight theme
# ---------------
#default
#darker
#pale night
#light
#ocean (since v1.5.5)
highlight_theme: pale night

code_word_wrap: false

highlight:
  enable: true
  line_number: true 
  auto_detect: false
  tab_replace:

# Nav settings
# see the icon_name in fontawesome website.
# And you need to add the `fa` or `fab` prefix by your self.
# ---------------
social:
# github: https://github.com/git-single-lee
#   weibo fab: https://weibo.com/coolqiLi
#   rss fas: https://Molunerfinn/atom.xml

# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 10

# Local search
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#local-search
# ---------------
local_search:
  enable: true

# MathJax
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#mathjax
# ---------------
mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# KaTeX
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#katex
# ---------------
katex:
  enable: false
  cdn:
    css: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  hide_scrollbar: true

# Toggle fireworks (IE >= 10)
# ---------------
fireworks: false

# Analysis
# ---------------
baidu_analytics: b7acef5306e54116ad8a99e8b753a92d
# Format: UA-xxxxxxxxx-x
# Example: UA-123456789-0
google_analytics:
# Format: G-xxxxxxxxx
# Example: G-0A12345678
google_analytics_MeasurementID:

# Tencent_analytics ID
tencent_analytics:

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    fontawesomev5: https://use.fontawesome.com/releases/v5.7.2/css/all.css

  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 

# Post info settings
# ---------------
avatar: /img/avatar.jpg
top_img: /img/blog-bg.jpg

post_meta:
  date_type: created # created or updated
  categories: true
  tags: true

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/additional-package-support.html#word-counting
wordcount:
  enable: true

toc:
  enable: true
  number: false

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/theme-config?id=auto-excerpt
auto_excerpt:
  enable: true
  length: 200

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  codeTheme: monokai
  # optional
  mouseWheel: true
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ""
  parallaxBackgroundSize: ""
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null
  loop: false
  autoSlide: false
  controlsBackArrows: 'faded'
  controlsLayout: 'bottom-right' # Determines where controls appear, "edges" or "bottom-right"
  progress: true
  showNotes: false
  autoPlayMedia: false
  backgroundTransition: 'fade'

sequence:
  # webfont:     # optional, the source url of webfontloader.js
  # snap:        # optional, the source url of snap.svg.js
  # underscore:  # optional, the source url of underscore.js
  # sequence:    # optional, the source url of sequence-diagram.js
  # css: # optional, the url for css, such as hand drawn theme 
  options: 
    theme: 
    css_class: 

flowchart:
  # raphael:   # optional, the source url of raphael.js
  # flowchart: # optional, the source url of flowchart.js
  options: # options used for `drawSVG`

# QR_code:
#     - itemlist:
#        img: /img/zfb.jpg
#        text: 支付宝打赏
#     - itemlist:
#        img: /img/wechat.jpg
#        text: 微信打赏

# Get a adv area for your post! You can put an adv or a music player and so on. It's up to you.
adv:
  enable: false
  info: <a href="https://www.vultr.com/?ref=7231808"><img src="https://www.vultr.com/media/banner_1.png" width="728" height="90"></a>

# if (theme.google_adsense && theme.google_adsense.enable)
#   script(data-ad-client="ca-pub-6845729157331145" async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js")

# Share System
# ---------------
addThis:
  enable: false
  #pubid: 

sharejs:
  enable: true
  # disabled_sites: 

# Comments System
# ---------------
disqus:
  enable: false 
  #shortname: 
  #count: 

laibili:
  enable: false
  uid: MTAyMC80NTc0My8yMjI1NA==

gitment:
   enable: true
   owner: 
   repo: 
   client_id: 7b4efbcd7027d15749d6 
   client_secret: 14b5d7e8580ee29f7aeca733a25c000795967448

gitalk:
  enable: false
  client_id: 4ddbf07faadeded6a7f0
  client_secret: 70a7a67c1e13762c3d1a00030ee92a69d21a1b28
  repo: git-single-lee.github.io
  owner: git-single-lee
  admin: git-single-lee

####   Using this js for redirect to gitalk container after login
####   See https://github.com/gitalk/gitalk/issues/125
#   js: https://cdn.jsdelivr.net/gh/upupming/gitalk@36368e5dffd049e956cdbbd751ff96c28d8255cf/dist/gitalk.min.js

# valine comment system. https://valine.js.org
# valine:
#   enable: false # if you want use valine,please set this value is true
#   appId:  # leancloud application app id
#   appKey:  # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
#   verify: false # valine verify code (true/false)
#   recordip: false # whether record commentor's ip (true/false)
#   pageSize: 10 # comment list page size
#   avatar: mm # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
#   placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf

valine:
   # if you want use valine,please set this value is ture
   enable: false 
   # leancloud application app id
   appId: eedJikU7JeDetXjbjw27DWBz-gzGzoHsz 
   # leancloud application app key
   appKey: woFTBOpMKS9EASNUpbaA9Jvc
   # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
   notify: false 
   # valine verify code (true/false)
   verify: false 
   # comment list page size
   pageSize: 10
   # gravatar style https://valine.js.org/#/avatar   
   avatar: mm
   # i18n: zh-cn/en
   lang: zh-cn
   # valine comment input placeholder(like: Please leave your footprints )#   guest_info: nick,mail,link #valine comment header inf
   placeholder: Just go go 

# vssue:
  # enable: false # Set to true to enable
  # platform: github-v4
  # owner:
  # repo:
  # clientId:
  # clientSecret: # only required for some of the platforms
  # autoCreateIssue: false # Auto create issue on platform (github/...)
  # baseURL: "" # For self-hosted gitlab/bitbucket only, see here: https://vssue.js.org/options/#baseurl
  # perPage: 10 # How much comment/page
  # labels: 'Vssue'

# waline comment system. https://waline.js.org/
# waline:
  # enable: true
  # serverURL: ''
  # lang: zh-CN
  # avatar: ''

# Footer Settings
# ---------------
since: 2015

footer_custom_text: hitokoto

ICP:
  enable: false
  #text: 

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file"></i>
  page_pv_footer:

# canvas_ribbon
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false

# Sidebar Settings
# ---------------
# In the sidebar, you can set some links to your friends or some web pages.
# Set the links title
#links_title: one more thing
#links:
# Name: url
#  AndroidDeveloper: https://developer.android.google.cn/
#  AndroidStudio: http://www.android-studio.org/
#  小二哥的 Android 站: https://www.jianshu.com/u/fd0b722ce11f

# Follow Me Button
follow:
  enable: true
  url: 'https://lishuaiqi.top'
  text: 'Follow Me'


# controls the sidebar showing or hidden in different pages
# all/index/post/index-none/post-none/hidden
sidebar_display: all 

# Ads
# ---------------
# Google Adsense
google_adsense:
  enable: false
  js: //pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-6845729157331145
  enable_page_level_ads: true


# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:

# Bing Webmaster tools verification setting
# See: https://www.bing.com/webmaster/
bing_site_verification:

# Yandex Webmaster tools verification setting
# See: https://webmaster.yandex.ru/
#yandex_site_verification:

# Baidu Webmaster tools verification setting
# See: https://ziyuan.baidu.com/site/
baidu_site_verification:

# 360 Webmaster tools verification setting
# see http://zhanzhang.so.com/
qihu_site_verification:

# avoid baidu transformation
disable_baidu_transformation: true

# 404 Page SubTitle
404Text:
